### PR TITLE
enable formData for request

### PR DESCRIPTION
**Pull request by iancrowther**
Hey,

I have been looking into this module and realised it always defaults to JSON.  Bulk import requires CSV via formData so I have had a go at a fix.

This PR introduces a breaking change so I'm happy to further discuss approaches.

### CODE REVIEW

**Comment by confuser** [comment]
Thanks for the contribution 😃 Open to accepting a breaking change alongside a major version bump. Could you cover this with a few tests please?

**Comment by iancrowther** [comment]
good shout on the tests! Let me know if you need more..

**Comment by confuser** [comment]
LGTM. Published as `v3.0.0`

**Comment by iancrowther** [comment]
Ah! I need to update the README!! Will drop that in later today

**Pull request merged**
