### PR TITLE
Update end-points, expose baseUrl as config

### PR DESCRIPTION
**Pull request by JohnField**
This repo hasn't been updated for a while - going by https://docs.npmjs.com/getting-started/semantic-versioning may need a version bump due to new option.

Am reasonably new to node - please advise if a new semver is needed - thanks.

### CODE REVIEW

**Comment by confuser** [comment]
Hi. Thanks for this. Looks like there's quite a few breaking changes on the dotmailer side. I no longer use dotmailer, so I'm out of the loop in terms of these changes. Having a brief read through looks like these are correct.

Yes, this would need releasing as a new major version, but that's something I can do on release/publish.

Looks like the tests are failing due to linting errors, could you fix those? Once everything is passing, I'll merge and release as 2.0.0

**Comment by JohnField** [comment]
Thanks for the prompt feedback!
Had checked jshint, but not checkStyle; have added `precommit` to automate these.

However, now having issues with 'hoek' - possibly due to age of dependencies (lots of deprecated and strict errors).

If these are not packages you're familiar with, I can investigate?

**Comment by confuser** [comment]
Fantastic. I'll merge this in shortly.

**Comment by confuser** [comment]
Published as v2

**Pull request merged**
